import { Component } from '@angular/core';

@Component({
  selector: 'product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent {
 products = [
  {
    id: 1,
    name: "Nike React Infinity Run Flyknit",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nisi, vel fugiat reiciendis inventore iste voluptas.",
    brand: "NIKE",
    gender: "MEN",
    category: "RUNNING",
    size: [6,7,8,9,10],
    color: ["White", "Blue", "Black"],
    price: 160,
    is_in_inventory: true,
    items_left: 3,
    imageUrl: "https://www.nike.com/w/nike-infinity-run-shoes-9g2tvzy7ok?utm_source=chatgpt.com",
    slug: "nike-react-infinity-run-flyknit"

  },
  {
    id: 2,
    name: "Adidas Ultraboost 22",
    description: "Boost cushioning and Primeknit upper for premium comfort and performance.",
    brand: "ADIDAS",
    gender: "MEN",
    category: "RUNNING",
    size: [7, 8, 9, 10, 11],
    color: ["Black", "Grey"],
    price: 180,
    is_in_inventory: true,
    items_left: 5,
    imageUrl: "#",
    slug: "adidas-ultraboost-22"
  },
  {
    id: 3,
    name: "Puma Flyer Runner",
    description: "Affordable lightweight running shoes for daily workouts and casual wear.",
    brand: "PUMA",
    gender: "MEN",
    category: "RUNNING",
    size: [6, 7, 8, 9],
    color: ["Red", "Black"],
    price: 75,
    discountedPrice: 140,
    is_in_inventory: true,
    items_left: 10,
    imageUrl: "#",
    slug: "puma-flyer-runner"
  },
  {
    id: 4,
    name: "Nike Air Zoom Pegasus 39",
    description: "Versatile running shoes with responsive cushioning for long distances.",
    brand: "NIKE",
    gender: "WOMEN",
    category: "RUNNING",
    size: [5, 6, 7, 8, 9],
    color: ["Pink", "White", "Black"],
    price: 140,
    is_in_inventory: true,
    items_left: 8,
    imageUrl: "#",
    slug: "nike-air-zoom-pegasus-39"
  },
  {
    id: 5,
    name: "Adidas Gazelle",
    description: "Classic sneakers with suede upper, perfect for casual wear.",
    brand: "ADIDAS",
    gender: "MEN",
    category: "CASUAL",
    size: [7, 8, 9, 10],
    color: ["Blue", "Grey"],
    price: 100,
    discountedPrice: 180,
    is_in_inventory: true,
    items_left: 12,
    imageUrl: "#",
    slug: "adidas-gazelle"
  },
  {
    id: 6,
    name: "Reebok Nano X1",
    description: "Cross-training shoes built for strength training and flexibility.",
    brand: "REEBOK",
    gender: "MEN",
    category: "TRAINING",
    size: [6, 7, 8, 9, 10, 11],
    color: ["Black", "White"],
    price: 130,
    is_in_inventory: false,
    items_left: 0,
    imageUrl: "#",
    slug: "reebok-nano-x1"
  },
  {
    id: 7,
    name: "Nike Metcon 8",
    description: "Stable training shoes designed for weightlifting and HIIT workouts.",
    brand: "NIKE",
    gender: "WOMEN",
    category: "TRAINING",
    size: [5, 6, 7, 8],
    color: ["Purple", "Grey"],
    price: 150,
    discountedPrice: 190,
    is_in_inventory: true,
    items_left: 4,
    imageUrl: "#",
    slug: "nike-metcon-8"
  },
  {
    id: 8,
    name: "Under Armour Charged Assert 9",
    description: "Durable shoes with Charged Cushioning midsole for runners.",
    brand: "UNDER ARMOUR",
    gender: "MEN",
    category: "RUNNING",
    size: [7, 8, 9, 10, 11],
    color: ["Black", "Red"],
    price: 90,
    is_in_inventory: true,
    items_left: 7,
    imageUrl: "#",
    slug: "ua-charged-assert-9"
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    description: "Timeless basketball-inspired sneakers with classic leather design.",
    brand: "NIKE",
    gender: "UNISEX",
    category: "CASUAL",
    size: [6, 7, 8, 9, 10, 11],
    color: ["White", "Black"],
    price: 110,
    discountedPrice: 200,
    is_in_inventory: true,
    items_left: 15,
    imageUrl: "#",
    slug: "nike-air-force-1"
  },
  {
    id: 10,
    name: "Adidas Superstar",
    description: "Iconic shell-toe sneakers perfect for streetwear.",
    brand: "ADIDAS",
    gender: "UNISEX",
    category: "CASUAL",
    size: [5, 6, 7, 8, 9, 10],
    color: ["White", "Black"],
    price: 95,
    is_in_inventory: true,
    items_left: 6,
    imageUrl: "#",
    slug: "adidas-superstar"
  },
  {
    id: 11,
    name: "Asics Gel-Kayano 28",
    description: "Stability running shoes with GEL cushioning for long-distance comfort.",
    brand: "ASICS",
    gender: "MEN",
    category: "RUNNING",
    size: [7, 8, 9, 10, 11],
    color: ["Blue", "Orange"],
    price: 160,
    discountedPrice: 130,
    is_in_inventory: true,
    items_left: 9,
    imageUrl: "#",
    slug: "asics-gel-kayano-28"
  },
  {
    id: 12,
    name: "New Balance 574",
    description: "Retro-inspired sneakers combining comfort and casual style.",
    brand: "NEW BALANCE",
    gender: "WOMEN",
    category: "CASUAL",
    size: [5, 6, 7, 8, 9],
    color: ["Grey", "Pink"],
    price: 85,
    is_in_inventory: true,
    items_left: 13,
    imageUrl: "#",
    slug: "new-balance-574"
  },
  {
    id: 13,
    name: "Converse Chuck Taylor All Star",
    description: "Classic canvas high-top sneakers, versatile for everyday wear.",
    brand: "CONVERSE",
    gender: "UNISEX",
    category: "CASUAL",
    size: [6, 7, 8, 9, 10, 11],
    color: ["Black", "White", "Red"],
    price: 60,
    discountedPrice: 110,
    is_in_inventory: true,
    items_left: 20,
    imageUrl: "#",
    slug: "converse-chuck-taylor"
  },
  {
    id: 14,
    name: "Skechers Go Walk 6",
    description: "Comfort-focused slip-on walking shoes with cushioned midsole.",
    brand: "SKECHERS",
    gender: "WOMEN",
    category: "WALKING",
    size: [5, 6, 7, 8],
    color: ["Grey", "Blue"],
    price: 70,
    is_in_inventory: true,
    items_left: 11,
    imageUrl: "#",
    slug: "skechers-go-walk-6"
  },
  {
    id: 15,
    name: "Fila Disruptor II",
    description: "Chunky retro sneakers with bold design for casual streetwear.",
    brand: "FILA",
    gender: "WOMEN",
    category: "CASUAL",
    size: [5, 6, 7, 8, 9],
    color: ["White", "Pink"],
    price: 85,
    is_in_inventory: true,
    items_left: 14,
    imageUrl: "#",
    slug: "fila-disruptor-ii"
  }
];
}
